### ISSUE TITLE
empty string surprise

### ISSUE THREAD

**Issue by harold** [noprompt/garden#169]
Hi! Thanks for garden, it's really fun and we use it every day.

Today I hit the following:
```
> (garden.core/css [:.row:after {:content "" :clear :both}])
.row:after {
  content: ;
  clear: both;
}
```

We had the above, and got the emitted invalid css, and experienced some rendering anomalies in various browsers.

Found a workaround of:
```
> (garden.core/css [:.row:after {:content "\"\"" :clear :both}])
.row:after {
  content: "";
  clear: both;
}
```

Is this expected?

**Comment by noprompt** [comment]
I’m glad you’re enjoying the library. 👍

> Is this expected?

Yes. I think what you want in that case is `”’’”` instead of a blank string. Since strings are an “escape hatch” for raw CSS values, you’ll need to use the single quotes for things like `content`. Typically, I use `pr-str` with a string for this sort of thing. 

Let me know if this is helpful and if there’s any other questions I can answer.

**Comment by harold** [comment]
@noprompt - thanks for the explanation. I will keep this in mind.

@charlesg3 - perhaps relevant to your interests.
