### ISSUE TITLE
Drop CLJX in favor of CLJC

### ISSUE THREAD

**Issue by noprompt** [noprompt/garden#77]

**Comment by priyatam** [comment]
@noprompt I was able to migrate my garden project (mesh) into cljc. I'd be happy to take over this migration.

**Comment by noprompt** [comment]
@priyatam If you're up for it that'd be awesome!

**Comment by priyatam** [comment]
@noprompt I've been working on this for the past two days. The migration is turning out to be non-trivial since we have to migrate not only clix but also tests and repl infrastructure. I'm positive the end result will be much leaner. Expect a big PR which will unify folder structures, and use a single cljc codebase, the new [cljs.test](https://github.com/clojure/clojurescript/wiki/Testing), and a brand new node repl workflow.

**Comment by jeluard** [comment]
@priyatam Cool stuff! Let me know when you have something running I'll be happy to test. You might want to consider [doo](https://github.com/bensu/doo) for running `cljs.test`, works great.

Also please consider removing [record?](https://github.com/noprompt/garden/blob/2e1daa64f6b98b8ac9c0c027231b2ae3efe0390a/src/cljx/garden/util.cljx#L86) as it's bundled now.

**Comment by noprompt** [comment]
@priyatam Thanks for taking up this challenge. I wish I had some more time to help you with it but I've been very busy. I'll keep an eye on this but do let me know if you decide not to finish it or if you have any questions. I think once this is good we can begin to work towards eliminating the `arithmetic` and `color` namespaces and using the standalone libraries I've extracted.

I know you've mentioned some new REPL stuff (I haven't had a chance to review it yet) but try and keep this PR focused on just the migration to CLJC. That will make it easier to digest.

**Comment by priyatam** [comment]
@noprompt @jeluard thanks for the tips. I just sent the PR. I wasn't able to work with the existing repls or tests, so I had to simplify project.clj to streamline the workflows on 1.7. I hope you agree the repl changes were necessary to simplify and accommodate the rapid changes in the Cljs ecosystem.
