### ISSUE TITLE
Idea: "Inlined" styles that get composed later

### ISSUE THREAD

**Issue by GetContented** [noprompt/garden#80]
Using hiccup, I wonder if it'd be possible to use hiccup (or other things that use hiccup-syntax such as Reagent) and garden together to make an app where CSS is specified at the tag (or component) level, and when the page is compiled or possible on page load, the CSS is built into one CSS file, and selectors and/or matching ids and/or classes are generated and connected up as required.

Does this sound like a ridiculous idea?

Using Reagent or somesuch component building framework (freagent or hoplon for example), it feels to me like it'd encourage the building of semantic design languages between designers and coders working together on the same project. It'd give both the freedom to move things around without stepping on the others' toes so much, potentially. I wonder :)

I'm not really sure where this would go, though. I guess Garden would at least need to be aware of it to allow the specification of class and id names on the fly so to speak.

**Comment by wildermuthn** [comment]
So I'm in the middle of building something like this. I'm generated classes on the fly, using garden to create css, and using goog.cssom to add css at runtime. Looks something like this:

![image](https://www.dropbox.com/s/noy9r321vbccsp7/Screenshot%202015-08-30%2023.58.23.png?dl=1)

I'm thrilled at the possibilities, but a little wary about performance issues. It takes about 2 ms to write one rule of css at runtime. Profiling suggests this is a browser issue (writing css at runtime) rather than a garden issue. 

I'm thinking that server-side rendering of html and css might be the answer.

**Comment by noprompt** [comment]
@wildermuthn I have done a lot of experimentation with `goog.cssom` and Garden but I haven't done much profiling and I certainly didn't encounter poor performance.  2ms per rule seems a little high. I'd need to know more about your approach to understand how you're getting these results.

Also, in the future, please use markdown for code samples instead of screenshots.

**Comment by wildermuthn** [comment]
Using Chrome's profiler, I get about 1.6ms for garden's make-class-string, and .3ms for goog.cssom's addCssRule.I don't think that's particularly bad for one operation, but wondering whether that means I'd need to be careful about the way I go about generating rules.

(image) [https://www.dropbox.com/s/x58h7ts34k34jgk/Screenshot%202015-09-02%2017.34.34.png?dl=0]

**Comment by noprompt** [comment]
I have a library for working with the CSSOM that I plan to release as a separate library in the future. I'm glad this was shared and I hope I can deliver something in the year ahead.

**Comment by GetContented** [comment]
@wildermuthn Sorry, but I couldn't quite work out how your approach uses hiccup at the **HTML tag level**. It seems to just be hiccup and garden?
