### ISSUE TITLE
Better syntax for complex shared styles

### ISSUE THREAD

**Issue by WorldsEndless** [noprompt/garden#89]
Right now I can execute: 

```clojure
 (css [:.navbar-inverse [:.navbar-nav [:> [:.active [:> [:a
                                                         :.navbar-inverse [:.navbar-nav [:> [:.open [:> [:a
                                                           {:color "#FFF"}]]]]]]]]]]])
;; ".navbar-inverse .navbar-nav > .active > a .navbar-nav > .open > a, .navbar-inverse .navbar-nav > .active > .navbar-inverse .navbar-nav > .open > a {\n  color: #FFF;\n}"
```

It would be far nicer if (css) could take a vector of vectors with a concluding map, where each vector specifies the selector. Done right, this should be fully reverse-compatible so as not to break existing code, but would be an excellent feature. e.g.: 

```clojure
(css   [[:.navbar-inverse [:.navbar-nav [:> [:.open [:> [:a]]]]]]
        [:.navbar-other]
        {:background-image "none"}])
;; ".navbar-inverse .navbar-nav > .open > a, .navbar-other {background-image: 'none'}"
```

**Comment by noprompt** [comment]
@WorldsEndless Actually a vector can't be used because it creates ambiguity in certain cases e.g. there wouldn't be a way to tell the difference between a rule and a selector. However, I think it might be possible to use a set which, overall, is much better than a vector because of it's properties. I would be open to review something which cleanly integrated. I'd much rather have something like `#{:a [:b :c] :d}` being equivalent to `a, b c, d`.

I really screwed up the design by special casing the first _n_ non-collection elements of the vector as being a selector.

**Comment by WorldsEndless** [comment]
I think the answer is sufficient on this. Thanks!
